### PR TITLE
HTML escaping

### PR DESCRIPTION
**Pull request by campfireman**
Changes:
- include bleach dependency
- escaping for form and model field
- updated readme
- simple test cases

### CODE REVIEW

**Comment by Surgo** [comment]
@lqez Can you release latest version to pypi 🙇 ?

**Comment by lqez** [comment]
@Surgo Oh my! I will do it today. Thanks.

**Comment by Surgo** [comment]
☺️

**Comment by tylerecouture** [comment]
Any chance of a release with this PR fix?  Thanks!

**Pull request merged**
