### PR TITLE
bootstrap 3.3.5

### PR DESCRIPTION
**Pull request by pincoin**
http://summernote.org/getting-started/
bootstrap update 3.3.5 from 3.1.1
jquery version is NOT updated yet because it depends on jquery.ui.widget.js, jquery.iframe-transport.js and jquery.fileupload.js.

### CODE REVIEW

**Comment by pincoin** [comment]
bootstrap 3.3.7, jquery file upload 9.18.0,  jquery 1.12.4 (latest versions)

juqery 2.2.4 works, but jquery 3.x doesn't work with jquery file upload library.
jquery 2.x or 3.x is not compatible for IE6, IE7, IE8.

**Comment by lqez** [comment]
Thanks @pincoin ! Could you rebase these commits into clean one?

**Comment by pincoin** [comment]
I clicked 'rebase' in PyCharm menu, but I'm not sure if I've done correctly. :-(

**Comment by lqez** [comment]
Thanks a lot! Actually, these PR has 2 different purposes - one for translation and one for updating external files. But I just squashed it into one. Thank you for your understanding.

**Pull request merged**
