### PR TITLE
Security fixes & UserPassesTestMixin in SummernoteUploadAttachment

### PR DESCRIPTION
**Pull request by wuuuduu**
1) Use UserPassesTestMixin in SummernoteUploadAttachment view
2) Security fixes:
   a) disable attachment module in the upload view
   b) validate if file is an image (using Pillow)

### CODE REVIEW

**Comment by wuuuduu** [comment]
I think we should drop support for Django 1.8
https://www.djangoproject.com/download/#supported-versions

**Comment by lqez** [comment]
Wow, awesome commits. But could you please remove 'version up' from your pull request? That will be done by the next release.

**Comment by wuuuduu** [comment]
> Wow, awesome commits. But could you please remove 'version up' from your pull request? That will be done by the next release.

`version_info = (0, 8, 11, 4, 1)`
and in CHANGES:
`0.8.11.41 - Security fixes and CustomUserPassesTestMixin in SummernoteUploadAttachment view`
?:)

**Comment by wuuuduu** [comment]
@lqez ping

**Comment by lqez** [comment]
@wuuuduu Thanks a lot. I changed a little to remove PIL dependency from the code.

**Comment by wuuuduu** [comment]
> @wuuuduu Thanks a lot. I changed a little to remove PIL dependency from the code.
> Ref: [b5bd104](https://github.com/summernote/django-summernote/commit/b5bd104e873bc1a189ddda65106790225b1aa303)

thanks!

**Pull request merged**
