### PR TITLE
Removed deprecated patterns syntax

### PR DESCRIPTION
**Pull request by claudep**
Django 1.10 won't support the deprecated django.conf.urls.patterns.

### CODE REVIEW

**Comment by lqez** [comment]
Thanks! I'll add a test for it (If 1.10 is available for testing) and merge it after that.

**Comment by lqez** [comment]
@claudep How can we test django 1.10 (I can't find it on pypi) in handy way?
Please review our tox(https://github.com/summernote/django-summernote/blob/master/tox.ini).

**Comment by claudep** [comment]
Django 1.10 is Django current master branch. It won't appear on pypi until the alpha release (planned for May 2016).
See https://github.com/django/django-localflavor/blob/master/tox.ini for an example of testing on master.
You could also decide that if current tests are passing with this patch, it could be committed...

**Comment by lqez** [comment]
Thanks! I'll review it asap.

**Comment by claudep** [comment]
See also the deprecation notice at the top of https://docs.djangoproject.com/en/1.9/ref/urls/

**Comment by lqez** [comment]
@claudep Thanks! I just released a new version with django master(1.10) test.

**Comment by claudep** [comment]
Nice, thanks!

**Pull request merged**
