### PR TITLE
Add note about non-image uploads in README

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Might save the time I searched for this for some users :-)

**Comment by lqez** [comment]
@claudep thank you for contributing.
This is just a my curiosity, how could we add `normal` file attachment on django-summernote? I thought normal files are not a business of summernote, but django `form` has to do something for it.

**Comment by claudep** [comment]
I would totally understand that you decide that this is not the job of django-summernote. On the other side, we could consider an uploaded file as a specific case of the image upload, except that the displayed representation is `<a href="file"></a>` instead of ``.

**Comment by lqez** [comment]
Displaying the name of file is enough? It would be looking better if we have a free icon package for various mime types. Do you have an idea?

**Comment by claudep** [comment]
Ah, of course we can then improve the feature with icons and such. Nice to have, but not necessarily a must in a first step.

**Comment by lqez** [comment]
@claudep got it. Then I'll **C L O S E** after adding a feature for handling normal file. Grrrrrr

**Comment by lqez** [comment]
To achieve this,
 - [ ] Create a plugin for normal file uploading on summernote
 - [ ] Add button for it (as default)

**Comment by lqez** [comment]
Now I can focus on this issue. So I just merged it.

**Pull request merged**
