### PR TITLE
- travis-ci build error fix

### PR DESCRIPTION
**Pull request by pincoin**
Hello,

I just removed "setuptools" in order not to install for travis-ci test.

I'm not sure what's wrong, but it now builds successfully.

[travis-ci build result](https://travis-ci.org/pincoin/django-summernote)

Thank you.

### CODE REVIEW

**Comment by lqez** [comment]
Thank you for contribution. However, do we have to remove `setuptools` from the configuration? I added this dependency to use `tox` properly. (when I created travis configuration at first, travis' setuptools version was too old to use tox)

Could you share the failure result caused by `setuptools` installation?

**Comment by lqez** [comment]
@pincoin like this? https://travis-ci.org/summernote/django-summernote/jobs/269869911

**Comment by pincoin** [comment]
That's it. 

I think "setuptools" has this issue, but I'm not sure how I fix it correctly. That's why I just deleted.

[#1085](https://github.com/pypa/setuptools/pull/1085)
[#1086](https://github.com/pypa/setuptools/pull/1086)
...

Thank you.

**Comment by lqez** [comment]
I browsed other projects and build results related with this issue, I decided to remove `setuptools` from travis test. Thank you!

**Pull request merged**
