### PR TITLE
In Admin app, set Attachment instance name to filename as default.

### PR DESCRIPTION
**Pull request by stvkas**
The name field in the Attachment model is set to the filename when a model instance is created through the [upload_attachment function](https://github.com/summernote/django-summernote/blob/master/django_summernote/views.py#L30). However, if an Attachment instance was created through the Admin app, via `AttachmentAdmin`, then the name field defaulted to `None`. 

This pull request assigns the name field of an Attachment instance to the filename if this field is falsey when an attachment is uploaded through the Admin app. It also includes an addition to `.gitignore` to exclude a `venv` directory for those who develop in isolated Python environments with [virtualenv](https://pypi.python.org/pypi/virtualenv).

### CODE REVIEW

**Comment by stvkas** [comment]
Does anyone know why the Travis CI build failed? I'm pretty stumped.

**Comment by lqez** [comment]
Sorry @stvkas, current build setting for the master version of django looks like not in good condition.

**Comment by lqez** [comment]
I fixed the test and it will be built well. Let me see...

**Comment by lqez** [comment]
@stvkas Thank you for contribution!

**Comment by stvkas** [comment]
@lqez Your welcome! I use this app for a project at work, so hopefully I'll be able to contribute more back to the project.

**Pull request merged**
