### PR TITLE
Fixes #84 import_module should be imported from standard library

### LINKED ISSUE #84: Deprecated module in Django 1.9
```
django_summernote/models.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module
```

### PR DESCRIPTION
**Pull request by dhirajt**

### CODE REVIEW

**Comment by lqez** [comment]
@dhirajt Thanks!
And I also added a test env for django 1.9, but we do not have any 1.9 on pypi :(
See : https://github.com/summernote/django-summernote/pull/99

**Comment by dhirajt** [comment]
@lqez Sorry, i didn't get you. What's need to release this on pypi?

**Comment by lqez** [comment]
@dhirajt I just released `0.6.16` ! yey!
https://pypi.python.org/pypi/django-summernote

**Comment by dhirajt** [comment]
@lqez Brilliant! Thanks a lot! :+1:

**Pull request merged**
